### ISSUE TITLE
ImportError: cannot import name 'Client' from partially initialized module 'dnsimple'

### ISSUE THREAD

**Issue by mecrayavcin** [dnsimple/dnsimple-python#438]
```
from dnsimple import Client
from dnsimple.struct import Contact, DomainRegistrationRequest

# Obtain your API token and Account ID
# https://support.dnsimple.com/articles/api-access-token/
client = Client(access_token="TOKEN")

account_id = 9999999

# Check for domain availability
response = client.registrar.check_domain(
      account_id,
      'google.com'
  )

print(response.data.available)
```

RESULT:

nv) C:\Users\SEO\Desktop\Python>C:/Users/SEO/anaconda3/envs/mainEnv/python.exe "c:/Users/SEO/Desktop/Python/Projects/Domain Backorder/Backorder/dnsimple.py"
Traceback (most recent call last):
  File "c:\Users\SEO\Desktop\Python\Projects\Domain Backorder\Backorder\dnsimple.py", line 1, in <module>
    from dnsimple import Client
  File "c:\Users\SEO\Desktop\Python\Projects\Domain Backorder\Backorder\dnsimple.py", line 1, in <module>
    from dnsimple import Client
ImportError: cannot import name 'Client' from partially initialized module 'dnsimple' (most likely due to a circular import) (c:\Users\SEO\Desktop\Python\Projects\Domain Backorder\Backorder\dnsimple.py)

At the first time when i tried it worked but after that try, i always get this error?
How can i fix this?
Thanks

**Comment by DXTimer** [comment]
The error message you're encountering, `ImportError: cannot import name 'Client' from partially initialized module 'dnsimple'`, is indicative of a circular import issue. In Python, a circular import occurs when two or more modules depend on each other, directly or indirectly.

Here's a breakdown of what's going wrong in your code, based on the provided traceback:

You have a file named `dnsimple.py` located at c:\Users\SEO\Desktop\Python\Projects\Domain Backorder\Backorder\dnsimple.py.
Inside this file, you're attempting to import `Client` from a module named `dnsimple` with the line from `dnsimple import Client`.
Python is getting confused because it's trying to import `Client` from `dnsimple.py`, which is the same file the import statement is in. Hence, it's a circular import: `dnsimple.py` is trying to import something from itself.

Suggested action:

Change the `dnsimple.py` to something else to avoid namespace conflicts.
